"""initial schema

Revision ID: 7ba944f645af
Revises: 
Create Date: 2025-12-21 21:54:27.168127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba944f645af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_slug', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='translationstatus'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('original_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_translations_chapter_language', 'translations', ['chapter_slug', 'language'], unique=False)
    op.create_index(op.f('ix_translations_chapter_slug'), 'translations', ['chapter_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_chapter_slug'), table_name='translations')
    op.drop_index('ix_translations_chapter_language', table_name='translations')
    op.drop_table('translations')
    # ### end Alembic commands ###
